name: guess_it_all_mobile
description: "Guess It All - A multiplayer word-guessing party game"
publish_to: 'none'
version: 1.1.2+7

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.68.0
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  uuid: ^4.5.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2

  # Firebase - Sync analytics to cloud
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0

  # Connectivity - Detect network status for sync
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "visuals/icone_guess_it_all.png"
  adaptive_icon_background: "#1a2744"
  adaptive_icon_foreground: "visuals/icone_guess_it_all.png"

flutter_native_splash:
  color: "#1a2744"
  image: visuals/icone_guess_it_all.png
  android: true
  ios: true
  android_12:
    color: "#1a2744"
    image: visuals/icone_guess_it_all.png
    fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/sounds/
    - assets/translations/
    - assets/translations/words/fr/

  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
